<?xml version="1.0" encoding="UTF-8"?>
<wsdl:definitions targetNamespace="http://dspace.org/xmlns/lni" xmlns:apachesoap="http://xml.apache.org/xml-soap" xmlns:impl="http://dspace.org/xmlns/lni" xmlns:intf="http://dspace.org/xmlns/lni" xmlns:soapenc="http://schemas.xmlsoap.org/soap/encoding/" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:wsdlsoap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:xsd="http://www.w3.org/2001/XMLSchema">
<!--WSDL created by Apache Axis version: 1.3
Built on Oct 05, 2005 (05:23:37 EDT)-->

   <wsdl:portType name="LNISoapServlet">

   </wsdl:portType>

   <wsdl:binding name="DSpaceLNISoapBinding" type="impl:LNISoapServlet">

      <wsdlsoap:binding style="rpc" transport="http://schemas.xmlsoap.org/soap/http"/>

   </wsdl:binding>

   <wsdl:service name="LNISoapServletService">

      <wsdl:port binding="impl:DSpaceLNISoapBinding" name="DSpaceLNI">

         <wsdlsoap:address location="http://localhost/dspace/lni/DSpaceLNI"/>

      </wsdl:port>

   </wsdl:service>

</wsdl:definitions>
